# Generated by Django 6.0.5 on 2026-05-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('town_hall', models.IntegerField()),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('co', 'Co-Leader'), ('elder', 'Elder'), ('member', 'Member')], max_length=20)),
                ('trophies', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
                ('war_attacks_used', models.IntegerField(default=0)),
                ('performance', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('inactive', 'Inactive')], max_length=20)),
            ],
        ),
    ]
