# Generated by Django 6.0.5 on 2026-05-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='donations_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
