# Generated by Django 6.0.5 on 2026-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0002_member_donations_received_member_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
