# Generated by Django 6.0.5 on 2026-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_member_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_type', models.CharField(choices=[('normal', 'Normal'), ('cwl', 'CWL')], max_length=20)),
                ('enemy', models.CharField(max_length=100)),
                ('enemy_badge', models.URLField(blank=True)),
                ('enemy_level', models.IntegerField(default=1)),
                ('size', models.IntegerField()),
                ('state', models.CharField(choices=[('preparation', 'Preparation'), ('in_battle', 'In Battle'), ('war_ended', 'War Ended')], max_length=20)),
                ('our_stars', models.IntegerField(default=0)),
                ('enemy_stars', models.IntegerField(default=0)),
                ('our_destruction', models.FloatField(default=0)),
                ('enemy_destruction', models.FloatField(default=0)),
                ('attacks_used', models.IntegerField(default=0)),
                ('attacks_total', models.IntegerField(default=0)),
                ('attacks_per_player', models.IntegerField(default=2)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
