# Generated by Django 6.0.5 on 2026-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0004_war'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='war',
            name='enemy_badge',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
