# Generated by Django 6.0.5 on 2026-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0005_alter_member_tag_alter_war_enemy_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='enemy_badge',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
