# Generated by Django 6.0.5 on 2026-05-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0006_alter_war_enemy_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_base', models.IntegerField()),
                ('stars', models.IntegerField(choices=[(0, '0 Star'), (1, '1 Star'), (2, '2 Star'), (3, '3 Star')])),
                ('destruction_percentage', models.FloatField(default=0)),
                ('attack_used', models.BooleanField(default=True)),
                ('attack_number', models.IntegerField(default=1)),
                ('war_type', models.CharField(max_length=20)),
                ('attack_time', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='clan.member')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='clan.war')),
            ],
        ),
    ]
