# Generated by Django 6.0.5 on 2026-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0007_attack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notice_type', models.CharField(choices=[('mail', 'Clan Mail'), ('recruitment', 'Recruitment'), ('war', 'War Reminder'), ('cwl', 'CWL'), ('promotion', 'Promotion')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
