# Generated by Django 6.0.5 on 2026-05-23 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0008_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='member',
            name='war_attacks_used',
        ),
        migrations.AddField(
            model_name='member',
            name='clan_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='eligible_for_cwl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='leader_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='league_icon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='league_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='missed_wars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='warning_level',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('coLeader', 'Co-Leader'), ('admin', 'Elder'), ('member', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='town_hall',
            field=models.IntegerField(default=1),
        ),
    ]
