# Generated by Django 6.0.5 on 2026-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0009_remove_member_last_active_remove_member_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='in_clan',
            field=models.BooleanField(default=True),
        ),
    ]
