# Generated by Django 6.0.5 on 2026-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0011_alter_war_result_alter_war_state_alter_war_war_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='enemy_badge',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
