# Generated by Django 6.0.5 on 2026-05-24 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0012_alter_war_enemy_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='attack_number',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='attack_time',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='attack_used',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='member',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='target_base',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='war_type',
        ),
        migrations.AddField(
            model_name='attack',
            name='attack_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attack',
            name='attacker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attacks_made', to='clan.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='defender_tag',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
