# Generated by Django 6.0.5 on 2026-05-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0013_remove_attack_attack_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='created_at',
            new_name='attack_time',
        ),
    ]
